version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    groups:
      gradle-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: swift
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-actions:
        patterns: ["*"]
